Change u₀ to u0
SciML/ReactionNetworkImporters.jl pull request #107
Opened 2023-10-07 01:26 UTC by TorkelE

Related to https://github.com/SciML/ReactionNetworkImporters.jl/issues/104

This is highly breaking though.

2023-10-07 01:28 UTC, isaacsas commented
If we want to add this there needs to be an overload so the old notation works and returns `u0` too. Then this isn’t breaking anything.

2023-10-07 01:38 UTC, TorkelE commented
Is that possible (without simultaneously supporting both fields)? I am only familiar with overloads for functions, so would be unsure how to do this.

2023-10-07 01:40 UTC, isaacsas commented
See `getproperty` and `setproperty`.

2023-10-07 01:42 UTC, TorkelE commented
But both `u₀` and `u0` which are given to these would have the same type (Symbol). Or you mean create new version of these functions on `ParsedReactionNetwork` that first check if the input is `u₀`, and if so calls it again with input `u0`?

2023-11-18 00:31 UTC, TorkelE commented
Updated. These overloads added:
```julia
# Ensures that `prnbng.u₀` works.
function Base.getproperty(prnbng::ParsedReactionNetwork, name::Symbol)
    if name === :u₀
        return getfield(prnbng, :u0)
    else
        return getfield(prnbng, name)
    end
end

# Ensures that `prnbng.u₀ = ...` works.
function Base.setproperty!(prnbng::ParsedReactionNetwork, name::Symbol, x)
    if name === :u₀
        return setfield!(prnbng, :u0, x)
    else
        return setfield!(prnbng, name, x)
    end
end
```
Given that parsed reaction networks are immutable, I don;t think the other one is needed though? 

I have also added a couple of tests in the tests file to check that (for some loaded network)
```julia
@test isequal(prnbng.u0, prnbng.u₀)
```

2023-12-29 19:07 UTC, isaacsas requested changes
One change then I'm happy to merge. Thanks!

2023-12-29 19:07 UTC, isaacsas commented on src/u0_index_change.jl
> +end
I think these can just be in the ReactionNetworkImporters.jl file. No need for a separate file.

2023-12-30 13:17 UTC, TorkelE commented
This one should be ready now.

2023-12-30 13:21 UTC, merged